require("async.test")

local Timers = require("timers")
local Callback = require("callback")
local wait = require("tests.utils.wait")

describe("Callback.every_limit", function()
  after_each(function()
    wait(5)
  end)

  async_it("works for result true", function()
    Callback.every_limit({ 3, 1, 2 }, 2, function(x, callback)
      Timers.set_timeout(function()
        callback(nil, x >= 1)
      end)
    end, function(err, result)
      assert.are.equal(err, nil)
      assert.are.equal(result, true)
      done()
    end)
  end)

  async_it("works for result false", function()
    Callback.every_limit({ "c", "a", "b" }, 2, function(x, callback)
      Timers.set_timeout(function()
        callback(nil, x == "c")
      end)
    end, function(err, result)
      assert.are.equal(err, nil)
      assert.are.equal(result, false)
      done()
    end)
  end)

  async_it("can early return", function()
    local calls = 0

    Callback.every_limit({ "f", "e", "d", "c", "a", "b" }, 2, function(x, callback, index)
      calls = calls + 1
      callback(nil, index < 3)
    end, function(err, result)
      assert.are.equal(err, nil)
      assert.are.equal(result, false)
      assert.are.equal(calls, 3)
      done()
    end)
  end)

  it("short circuit", function()
    local call_order = {}

    Callback.every_limit({ "a", "b", "c", "d", "e", "f" }, 2, function(x, callback, index)
      Timers.set_timeout(function()
        table.insert(call_order, x)
        callback(nil, index < 3)
      end, index * 15)
    end, function(err, result)
      table.insert(call_order, "callback")
      assert.equal(err, nil)
      assert.equal(result, false)
    end)

    wait(350, function()
      assert.are.same(call_order, { "a", "b", "c", "callback", "d" })
    end)
  end)

  async_it("can error", function()
    Callback.every_limit({ "a", "b", "c", "d", "e" }, 2, function(_, callback)
      Timers.set_timeout(function()
        callback("error")
      end)
    end, function(err, result)
      assert.are.equal(err, "error")
      assert.are.equal(result, nil)
      done()
    end)
  end)

  it("can be canceled", function()
    local call_order = {}
    Callback.every_limit({ "a", "b", "c", "d", "e" }, 2, function(x, callback, index)
      Timers.set_timeout(function()
        table.insert(call_order, x)
        if x == "c" then
          return callback(false, true)
        end
        callback(nil, true)
      end, index * 15)
    end, function()
      assert.True(false, "should not get here")
    end)

    wait(350, function()
      assert.are.same(call_order, { "a", "b", "c", "d" })
    end)
  end)
end)
